# Generated by Django 5.0 on 2023-12-05 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Время добавления')),
                ('price', models.DecimalField(decimal_places=20, max_digits=50, verbose_name='Цена')),
                ('image', models.TextField(max_length=1000, verbose_name='Изображение')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='shop_app.category', verbose_name='Категория')),
            ],
        ),
    ]
